### PR TITLE
Minor cleaning

### PR DESCRIPTION
**Pull request by VnC-**

### CODE REVIEW

**Comment by remram44** [comment]
For some reason the `%zu` format warns on GCC... (it's fine on VC++)

I still get warnings on `free(option_array)` in pyjava.c on VC++, I'm not sure how to fix these (if I change it from `const char**` to `char**` I get a warning on GCC when assigning). God I which these compilers would agree.

**Comment by remram44** [comment]
Thanks a ton!

**Comment by VnC-** [comment]
For me it's fine on debian gcc 4.4.5, 0 warnings on master branch.

**Comment by remram44** [comment]
gcc 4.5.2 here (MinGW)

```
gcc.exe -c native\convert.c -o build\native\convert.o

gcc.exe -c native\java.c -o build\native\java.o

gcc.exe -c native\javawrapper.c -o build\native\javawrapper.o
native\javawrapper.c: In function 'JavaMethod_call':
native\javawrapper.c:104:17: warning: unknown conversion type character 'z' in format
native\javawrapper.c:104:17: warning: format '%s' expects type 'char *', but argument 3 has type 'size_t'
native\javawrapper.c:104:17: warning: unknown conversion type character 'z' in format
native\javawrapper.c:104:17: warning: trop d'arguments pour le format
native\javawrapper.c: In function 'JavaClass_create':
native\javawrapper.c:469:17: warning: unknown conversion type character 'z' in format
native\javawrapper.c:469:17: warning: unknown conversion type character 'z' in format
native\javawrapper.c:469:17: warning: trop d'arguments pour le format

gcc.exe -c native\pyjava.c -o build\native\pyjava.o

gcc.exe -shared build\native\convert.o build\native\java.o build\native\javawrapper.o build\native\pyjava.o -o build\_pyjava.pyd
```

**Comment by VnC-** [comment]
No warnings with gcc 4.6.2 (MinGW) here

**Pull request merged**
